### ISSUE TITLE
Class renaming incomplete with B19 version

### ISSUE THREAD

**Issue by admiralspark** [KiameV/rimworld-modifyresearchtime#1]
Hello,

Following error message is reproducible with no mods active, all mods active, complete wipe and reload of Rimworld and all mods, etc.

> Could not find class ModifyResearchTime.Settings while resolving node ModSettings. Trying to use ChangeResearchSpeed.Settings instead. Full node: <ModSettings Class="ModifyResearchTime.Settings"><ModifyResearchTime.Factor>0.5</ModifyResearchTime.Factor><ModifyResearchTime.AllowTechAdvance>True</ModifyResearchTime.AllowTechAdvance></ModSettings>
> Verse.Log:Error(String, Boolean)
> Verse.ScribeExtractor:SaveableFromNode(XmlNode, Object[])
> Verse.Scribe_Deep:Look(Settings&, Boolean, String, Object[])
> Verse.Scribe_Deep:Look(Settings&, String, Object[])
> Verse.LoadedModManager:ReadModSettings(String, String)
> Verse.Mod:GetSettings()
> ChangeResearchSpeed.SettingsController:.ctor(ModContentPack)
> System.Reflection.MonoCMethod:InternalInvoke(Object, Object[], Exception&)
> System.Reflection.MonoCMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
> System.Reflection.MonoCMethod:Invoke(BindingFlags, Binder, Object[], CultureInfo)
> System.Activator:CreateInstance(Type, BindingFlags, Binder, Object[], CultureInfo, Object[])
> System.Activator:CreateInstance(Type, Object[], Object[])
> System.Activator:CreateInstance(Type, Object[])
> Verse.LoadedModManager:CreateModClasses()
> Verse.LoadedModManager:LoadAllActiveMods()
> Verse.PlayDataLoader:DoPlayLoad()
> Verse.PlayDataLoader:LoadAllPlayData(Boolean)
> Verse.Root:<Start>m__1()
> Verse.LongEventHandler:RunEventFromAnotherThread(Action)
> Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__1()

**Comment by admiralspark** [comment]
https://github.com/KiameV/rimworld-modifyresearchtime/blob/f3c08fcf458743e21e162ff36d2795ba70e06dc4/Source/HarmonyPatches.cs#L14

This may be the problem child.

**Comment by admiralspark** [comment]
This issue has not been resolved?

**Comment by KiameV** [comment]
I am not supporting version B19. At this point only supporting 1.2.

**Comment by KiameV** [comment]
It's possible you have a very old version of a setting file (from B19). If that's the case delete the file that's in your local user folder
`HKEY_CURRENT_USER/Software/Ludeon Studios/Rimworld/RimWorld by Ludeon Studios/Config`
look for the file named `Mod_<some numbers>_ChangeResearchSpeed_SettingsController.xml` and delete it
