### ISSUE TITLE
Changing research speed breaks save loading

### ISSUE THREAD

**Issue by Gazzoo-byte** [KiameV/rimworld-modifyresearchtime#3]
[HugsLog.txt](https://github.com/KiameV/rimworld-modifyresearchtime/files/6329993/HugsLog.txt)

Trying to load a save game which uses Dubs Mint Menus and Change Research Speed breaks save games, loading twice in a row sometimes works, sometimes causes a crash to desktop.

Modlist:
Harmony
Core
Royalty
Hugslib
Mod Manager
Change Reasearch Speed
RimSaves
Dubs Mint Menus

Reproduction steps:

1. Create colony
2. Begin research
3. Save
4. Restart Rimworld
5. Load save game

**Comment by KiameV** [comment]
This is an issue with mint menus
